settings:
  title: 'Status Page'
  url: 'https://status.tikvite.org' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 92 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: tikvite-org # unique identifier
    name: tikvite.org
    description: 'home sweet home' # default=empty
    url: 'https://tikvite.org' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: chat-tikvite-org
    name: Chat
    description: 'If it dies, it dies.'
    url: 'https://chat.tikvite.org'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: tikvite-duckdns-org
    name: DDNS
    description: 'just in case'
    url: 'https://tikvite.duckdns.org'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
